export const ACTION_TYPE = {
	SET_USER: 'SET_USER',
	LOGOUT: 'LOGOUT',
	SET_PRODUCT_DATA: 'SET_PRODUCT_DATA',
	SET_ALL_PRODUCTS: 'SET_ALL_PRODUCTS',
	OPEN_MODAL: 'OPEN_MODAL',
	CLOSE_MODAL: 'CLOSE_MODAL',
	RESET_PRODUCT_DATA: 'RESET_PRODUCT_DATA',
	SET_CART_ITEMS: 'SET_CART_ITEMS',
	SHOW_TOAST: 'SHOW_TOAST',
	HIDE_TOAST: 'HIDE_TOAST',
};
